### ISSUE TITLE
kernel version不能低于5.5.0吗？

### ISSUE THREAD

**Issue by sunyue-s** [NLPJCL/RAG-Retrieval#10]

**Comment by NLPJCL** [comment]
应该是可以的。请问下，您有修改了配置嘛？
我也有遇到过。如果多卡的训练是fsdp，没有遇到这个warning。但是如果更换为deepspeed，会出现这个warning。但是实测是没啥问题的。

**Comment by sunyue-s** [comment]
感谢回复，没有修改配置，报错：Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
除此之外还有一个问题，已安装torch2.2.1+cu118 transformer4.40.2 accelerate0.30.0，报错：Exception: Could not find the transformer layer class to wrap in the model. 是和安转的版本原因吗？

**Comment by NLPJCL** [comment]
您应该微调的是多语言版本的模型？需要修改下 fsdp 的 config 为对应多语言版本。


kernel 的提醒应该不影响效果。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月10日(周五) 上午9:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [NLPJCL/RAG-Retrieval] kernel version不能低于5.5.0吗？ (Issue #10)




 
感谢回复，没有修改配置，报错：Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
 除此之外还有一个问题，已安装torch2.2.1+cu118 transformer4.40.2 accelerate0.30.0，报错：Exception: Could not find the transformer layer class to wrap in the model. 是和安转的版本原因吗？

**Comment by sunyue-s** [comment]
> 您应该微调的是多语言版本的模型？需要修改下 fsdp 的 config 为对应多语言版本。 kernel 的提醒应该不影响效果。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年5月10日(周五) 上午9:47 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [NLPJCL/RAG-Retrieval] kernel version不能低于5.5.0吗？ (Issue #10) 感谢回复，没有修改配置，报错：Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher. 除此之外还有一个问题，已安装torch2.2.1+cu118 transformer4.40.2 accelerate0.30.0，报错：Exception: Could not find the transformer layer class to wrap in the model. 是和安转的版本原因吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

是的，已修改，再咨询一下您有碰到这个问题吗？RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.   已设置CUDA_VISIBLE_DEVICES=0在其他服务上是正常运行的。

**Comment by sunyue-s** [comment]
> 您应该微调的是多语言版本的模型？需要修改下 fsdp 的 config 为对应多语言版本。 kernel 的提醒应该不影响效果。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年5月10日(周五) 上午9:47 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [NLPJCL/RAG-Retrieval] kernel version不能低于5.5.0吗？ (Issue #10) 感谢回复，没有修改配置，报错：Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher. 除此之外还有一个问题，已安装torch2.2.1+cu118 transformer4.40.2 accelerate0.30.0，报错：Exception: Could not find the transformer layer class to wrap in the model. 是和安转的版本原因吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

好的感谢，已修改

**Comment by sunyue-s** [comment]
> 您应该微调的是多语言版本的模型？需要修改下 fsdp 的 config 为对应多语言版本。 kernel 的提醒应该不影响效果。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年5月10日(周五) 上午9:47 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [NLPJCL/RAG-Retrieval] kernel version不能低于5.5.0吗？ (Issue #10) 感谢回复，没有修改配置，报错：Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher. 除此之外还有一个问题，已安装torch2.2.1+cu118 transformer4.40.2 accelerate0.30.0，报错：Exception: Could not find the transformer layer class to wrap in the model. 是和安转的版本原因吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;
再请问一下，您有遇到：RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.  设置 CUDA_VISIBLE_DEVICES=0基本信息是没错的，是accelerate中有涉及device的问题还是回退到kernel version问题？

**Comment by NLPJCL** [comment]
https://github.com/NLPJCL/RAG-Retrieval/issues/3
请参考这个适配多gpu训练。如果还有问题，请提供下训练的脚本以及config文件。

**Comment by sunyue-s** [comment]
> #3 请参考这个适配多gpu训练。如果还有问题，请提供下训练的脚本以及config文件。

已修改num_processes: 1，依旧是只报错Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.版本问题

**Comment by sunyue-s** [comment]
> #3 请参考这个适配多gpu训练。如果还有问题，请提供下训练的脚本以及config文件。

已成功，感谢帮助！
