### ISSUE TITLE
为什么训练“m3e-base”模型loss为nan

### ISSUE THREAD

**Issue by huangt1** [NLPJCL/RAG-Retrieval#13]
我在相同参数下训练开源的m3e-base模型，但是loss从第一次迭代后就一直是nan，相同配置和参数下训练bge-base-zh-v1.5模型是正常的，这是为什么呢？
训练脚本如下：
CUDA_VISIBLE_DEVICES="0,1"   nohup  accelerate launch --config_file ../configs/default_fsdp.yaml train_embedding.py  \
--model_name_or_path "../models/m3e-base" \
--dataset "../datas/embedding/t2rank_100.json" \
--output_dir "../results/m3e-base" \
--batch_size 8 \
--lr 2e-5 \
--epochs 4 \
--save_on_epoch_end 1 \
--gradient_accumulation_steps 24  \
--log_with 'wandb' \
--warmup_proportion 0.1 \
--neg_nums 2 \
--temperature 0.02 \
--query_max_len 128 \
--passage_max_len 512 \
 >../logs/m3e-base.log &

**Comment by NLPJCL** [comment]
loss为nan，是说第一个epoch之后？还是第一个step开始就是nan呢？

**Comment by huangt1** [comment]
> loss为nan，是说第一个epoch之后？还是第一个step开始就是nan呢？

第一个step正常输出小数值，之后全都是nan

**Comment by NLPJCL** [comment]
> > loss为nan，是说第一个epoch之后？还是第一个step开始就是nan呢？
> 
> 第一个step正常输出小数值，之后全都是nan

建议两个两个思路尝试下。
1.先用我给的示例数据跑下，看下loss是否还是nan。排查下数据的原因。
2.降低学习率试试。

**Comment by huangt1** [comment]
> > > loss为nan，是说第一个epoch之后？还是第一个step开始就是nan呢？
> > 
> > 
> > 第一个step正常输出小数值，之后全都是nan
> 
> 建议两个两个思路尝试下。 1.先用我给的示例数据跑下，看下loss是否还是nan。排查下数据的原因。 2.降低学习率试试。

用你的数据没问题，改成自己的数据就这样了，现在换成bge-base-zh-v1.5也变成nan了，学习率调了也这样。
mixed_precision: fp16
gradient_accumulation_steps: 8
temperature: 0.02
log_with: wandb
neg_nums: 2
query_max_len: 256
passage_max_len: 512
train_dataloader total is : 1589
train_dataloader data_type is : triplet
val_dataloader total is : 681
val_dataloader data_type is : triplet
Detected kernel version 3.10.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum
 version or higher.
Start training for 2 epochs
Epoch 1/2 - loss: 1.154800 - lr: 0.000000:   0%|          | 6/1589 [00:02<11:22,  2.32it/s]
Epoch 1/2 - loss: nan - lr: 0.000000:   1%|          | 13/1589 [00:05<10:40,  2.47it/s]     
Epoch 1/2 - loss: nan - lr: 0.000000:   1%|▏         | 21/1589 [00:08<10:37,  2.46it/s]
Epoch 1/2 - loss: nan - lr: 0.000001:   2%|▏         | 27/1589 [00:11<10:33,  2.47it/s]
Epoch 1/2 - loss: nan - lr: 0.000001:   2%|▏         | 34/1589 [00:14<10:25,  2.47it/s]
Epoch 1/2 - loss: nan - lr: 0.000001:   2%|▏         | 37/1589 [00:15<10:17,  2.51it/s]

**Comment by NLPJCL** [comment]
应该是数据的原因，正例和负例的是怎么搞出来的呢？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月28日(周二) 晚上6:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [NLPJCL/RAG-Retrieval] 为什么训练“m3e-base”模型loss为nan (Issue #13)




    
loss为nan，是说第一个epoch之后？还是第一个step开始就是nan呢？
  
第一个step正常输出小数值，之后全都是nan
  
建议两个两个思路尝试下。 1.先用我给的示例数据跑下，看下loss是否还是nan。排查下数据的原因。 2.降低学习率试试。
  
用你的数据没问题，改成自己的数据就这样了，现在换成bge-base-zh-v1.5也变成nan了，学习率调了也这样。
 mixed_precision: fp16
 gradient_accumulation_steps: 8
 temperature: 0.02
 log_with: wandb
 neg_nums: 2
 query_max_len: 256
 passage_max_len: 512
 train_dataloader total is : 1589
 train_dataloader data_type is : triplet
 val_dataloader total is : 681
 val_dataloader data_type is : triplet
 Detected kernel version 3.10.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum
 version or higher.
 Start training for 2 epochs
 Epoch 1/2 - loss: 1.154800 - lr: 0.000000:   0%|          | 6/1589 [00:02<11:22,  2.32it/s]
 Epoch 1/2 - loss: nan - lr: 0.000000:   1%|          | 13/1589 [00:05<10:40,  2.47it/s]
 Epoch 1/2 - loss: nan - lr: 0.000000:   1%|▏         | 21/1589 [00:08<10:37,  2.46it/s]
 Epoch 1/2 - loss: nan - lr: 0.000001:   2%|▏         | 27/1589 [00:11<10:33,  2.47it/s]
 Epoch 1/2 - loss: nan - lr: 0.000001:   2%|▏         | 34/1589 [00:14<10:25,  2.47it/s]
 Epoch 1/2 - loss: nan - lr: 0.000001:   2%|▏         | 37/1589 [00:15<10:17,  2.51it/s]

**Comment by huangt1** [comment]
> 应该是数据的原因，正例和负例的是怎么搞出来的呢？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年5月28日(周二) 晚上6:28 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [NLPJCL/RAG-Retrieval] 为什么训练“m3e-base”模型loss为nan (Issue #13) loss为nan，是说第一个epoch之后？还是第一个step开始就是nan呢？ 第一个step正常输出小数值，之后全都是nan 建议两个两个思路尝试下。 1.先用我给的示例数据跑下，看下loss是否还是nan。排查下数据的原因。 2.降低学习率试试。 用你的数据没问题，改成自己的数据就这样了，现在换成bge-base-zh-v1.5也变成nan了，学习率调了也这样。 mixed_precision: fp16 gradient_accumulation_steps: 8 temperature: 0.02 log_with: wandb neg_nums: 2 query_max_len: 256 passage_max_len: 512 train_dataloader total is : 1589 train_dataloader data_type is : triplet val_dataloader total is : 681 val_dataloader data_type is : triplet Detected kernel version 3.10.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher. Start training for 2 epochs Epoch 1/2 - loss: 1.154800 - lr: 0.000000: 0%| | 6/1589 [00:02<11:22, 2.32it/s] Epoch 1/2 - loss: nan - lr: 0.000000: 1%| | 13/1589 [00:05<10:40, 2.47it/s] Epoch 1/2 - loss: nan - lr: 0.000000: 1%|▏ | 21/1589 [00:08<10:37, 2.46it/s] Epoch 1/2 - loss: nan - lr: 0.000001: 2%|▏ | 27/1589 [00:11<10:33, 2.47it/s] Epoch 1/2 - loss: nan - lr: 0.000001: 2%|▏ | 34/1589 [00:14<10:25, 2.47it/s] Epoch 1/2 - loss: nan - lr: 0.000001: 2%|▏ | 37/1589 [00:15<10:17, 2.51it/s] — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

正例数据是用大模型生成的问答对，负例是随机抽取的知识片段，例如：
{'query': '头尾轴的形成还依赖哪些特定的信号分子？', 'pos': '头尾轴的形成还依赖前脑是由胚孔背唇处中胚层的“组织者”产生的Follistatin。', 'neg': ['真菌类的连锁分析：着丝粒作图：lys*和lys~在第二次分裂后期时才分离，这时带有lys*的染色单体分向一极，而带有lys~的染色单体分向另一极。交叉发生在lys*/lys~与着丝粒之间，所以子囊型(3)或(4)是交换型。', "KpnI切割pBR322-SV40产生3'端黏性末端，并添加poly(dT)尾。接着，HpaI切去一侧poly(dT)尾，仅保留PvuⅡ位点附近的poly(dT)。"]}, 
{'query': '应激的细胞反应中，热休克蛋白的基本功能是什么？', 'pos': '热休克蛋白的基本功能是诱导表达。在各种应激原的作用下，细胞质中的变性蛋白质增多，这些变性蛋白的折叠发生改变，暴露出分子内部的疏水区域，从而导致HSP与其结合。HSP与受损伤蛋白质结合后释放出HSF单体，HSF单体再聚合成具有转录活性的三聚体，经过磷酸化修饰，HSF三聚体向核内转移并结合至hsp启动子区的HSE,激活hsp的转录，使HSP产生增多。', 'neg': ["50S亚基结构与功能\n50S亚基的结构显示蛋白质相对较少，肽基转移酶活性中心无蛋白质，P位点tRNA的2'-OH参与催化反应。RF1和RF2识别终止密码子，参与肽键切割。", '原核表达载体的基本调控元件：1.启动子：此外，在42℃高温状态，宿主菌内的热休克蛋白被激活，可能影响代谢或重组蛋白质。']}

目前，训练“bge-base-zh-v1.5”模型和最开始训练“m3e-base”模型出现的情况一样了，第一个step之后loss就一直是nan，但把“mixed_precision”从“fp16”改成“no”后，loss也不是nan了。

**Comment by NLPJCL** [comment]
没有遇到相同的情况。
把“mixed_precision”从“fp16”改成“no”后，loss也不是nan了。这样训练完后是否正常呢？

**Comment by NLPJCL** [comment]
换数据就没出现这种情况的话。还是建议打印出来数据，多看看，数据是否有问题。

**Comment by NLPJCL** [comment]
换数据就没出现这种情况的话。还是建议打印出来数据，多看看，数据是否有问题。

**Comment by huangt1** [comment]
> 没有遇到相同的情况。 把“mixed_precision”从“fp16”改成“no”后，loss也不是nan了。这样训练完后是否正常呢？

从训练数据来看是正常的，loss保持下降，验证集的结果也挺好。

**Comment by NLPJCL** [comment]
确实没遇到过这种情况，这里面设置与mixed_precision 有关的就是Accelerator，我的accelerate版本是0.27.2 。
您可以对齐看下mixed_precision是否可以，如果还是不行，那就不清楚是否与硬件有关了，我一般用v 100 32g以及a100 80g跑。
