### ISSUE TITLE
embedding微调时，tensorboard可视化参数问题

### ISSUE THREAD

**Issue by HuXiLiFeng** [NLPJCL/RAG-Retrieval#17]
https://github.com/NLPJCL/RAG-Retrieval/blob/master/rag_retrieval/train/embedding/train_embedding.py#L83
`accelerator.init_trackers('embedding', config=args)`
在该函数定义里，config是dict类型，但是这里的args是<class 'argparse.Namespace'>类型不符，报错：TypeError: hparam_dict and metric_dict should be dictionary.
按如下修改即可：
`accelerator.init_trackers('embedding', config=vars(args))`

**Comment by NLPJCL** [comment]
感谢提醒~
我这边默认用的是wandb来可视化，没有报过这个错误，您可以把执行的参数发下，我来试试。

**Comment by HuXiLiFeng** [comment]
> 感谢提醒~ 我这边默认用的是wandb来可视化，没有报过这个错误，您可以把执行的参数发下，我来试试。

直接执行的embedding下的train_embedding.sh，只是换了下模型地址，log_with改成tensorboard。其他参数没动

**Comment by NLPJCL** [comment]
> > 感谢提醒~ 我这边默认用的是wandb来可视化，没有报过这个错误，您可以把执行的参数发下，我来试试。
> 
> 直接执行的embedding下的train_embedding.sh，只是换了下模型地址，log_with改成tensorboard。其他参数没动

多谢，我回头测试下。确实没尝试过更换为tensorboard。
