### ISSUE TITLE
使用query-pos格式数据微调embedding，loss报错

### ISSUE THREAD

**Issue by HuXiLiFeng** [NLPJCL/RAG-Retrieval#19]
base模型：bge_large
训练数据格式:jsonl文件,每行：{"query":"ssss","pos":["xxx"]}
没改代码，按照readme微调embedding时报错：

> AttributeError: 'builtin_function_or_method' object has no attribute 'transpose'

报错代码见：https://github.com/NLPJCL/RAG-Retrieval/blob/master/rag_retrieval/train/embedding/model.py#L79
`sim_matrix = query_embeddings @ pos_doc_embeddings.unsqueeze.transpose(-1, -2)`
这里不用增加维度，修改为:
`sim_matrix = query_embeddings @ pos_doc_embeddings.transpose(-1, -2)`
即可正常训练

**Comment by NLPJCL** [comment]
这里确实有点问题，感谢您指出，我会近期修复下。

**Comment by NLPJCL** [comment]
已修复
