### ISSUE TITLE
Reranker 微调数据集准备？

### ISSUE THREAD

**Issue by huangjun11** [NLPJCL/RAG-Retrieval#21]
我使用 “query和正例以及难负例 ”格式数据集微调了embedding model，请问如果准备Reranker 微调数据集？您在介绍中提到了可以使用两种数据,请问有没有这两种数据的示例,以及应该如何准备.

**Comment by NLPJCL** [comment]
这个页面有例子。
https://github.com/NLPJCL/RAG-Retrieval/tree/master/rag_retrieval/train/reranker

**Comment by huangjun11** [comment]
您好，感谢回复，我看了您提供的页面，收获很大。另外，关于四分类数据，能否提供一个真实的数据示例，谢谢

**Comment by NLPJCL** [comment]
类似这种，
query1\tdoc1\t4
query2\tdoc2\t3

这里可以看细节的处理逻辑：
https://github.com/NLPJCL/RAG-Retrieval/blob/383dc5a88d65de9de2a7ea0067a1c34f1e90936f/rag_retrieval/train/reranker/data.py#L78

**Comment by huangjun11** [comment]
好的，谢谢
