### ISSUE TITLE
batch内随机负例 是在哪里实现的啊

### ISSUE THREAD

**Issue by HuXiLiFeng** [NLPJCL/RAG-Retrieval#23]
![Snipaste_2024-06-20_01-05-58](https://github.com/NLPJCL/RAG-Retrieval/assets/20320649/08308fb6-2f81-4e9e-84b1-aa804c74f586)

**Comment by NLPJCL** [comment]
向量模型
对于只有正例：
是在这一行实现的。把batch内其他query的正例作为当前query的随机负例。
https://github.com/NLPJCL/RAG-Retrieval/blob/77155083d8de9c9a7df451cf5fc1ca1046bafd9f/rag_retrieval/train/embedding/model.py#L115C1-L116C1
对于只有正例以及难负例，
是在这一行实现的，把batch内其他query的所有难负例，作为当前query的随机负例。
https://github.com/NLPJCL/RAG-Retrieval/blob/77155083d8de9c9a7df451cf5fc1ca1046bafd9f/rag_retrieval/train/embedding/model.py#L139
