### ISSUE TITLE
微调colbert之后，评测时遇到问题

### ISSUE THREAD

**Issue by HuXiLiFeng** [NLPJCL/RAG-Retrieval#25]
参考colbert目录下的readme，只是换了自己的数据，训完评测时，发现每次结果不一样
```
from sentence_transformers import SentenceTransformer, CrossEncoder, util
cross_encoder = CrossEncoder("./m3/model")
corpus = ["西安","太原","北京","海南"] 
top_res=cross_encoder.rank(query="陕西省的省会城市是哪个", documents=corpus, top_k=3, return_documents=True)
print(top_res)
```

1. 提示如下，这个是正常的吗

> Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at ./m3/model and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

2. 发现每次执行结果不一样，相同代码执行2词结果如下：

> [{'corpus_id': 0, 'score': 0.5507802, 'text': '西安'}, {'corpus_id': 2, 'score': 0.54930556, 'text': '北京'}, {'corpus_id': 1, 'score': 0.5357058, 'text': '太原'}]

> [{'corpus_id': 1, 'score': 0.5277521, 'text': '太原'}, {'corpus_id': 2, 'score': 0.5160099, 'text': '北京'}, {'corpus_id': 0, 'score': 0.4968127, 'text': '西安'}]

麻烦帮忙看下是什么原因呢

**Comment by HuXiLiFeng** [comment]
用readme里提供的方式就可以了。看了下应该是没有load colbert_linear参数 https://github.com/NLPJCL/RAG-Retrieval/blob/master/rag_retrieval/train/colbert/model.py#L184。sentence_transformers.CrossEncoder不能直接加载吗

**Comment by NLPJCL** [comment]
是的，colbert 非 cross-encoder 类型。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月21日(周五) 晚上6:36
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [NLPJCL/RAG-Retrieval] 微调colbert之后，评测时遇到问题 (Issue #25)




 
用readme里提供的方式就可以了。看了下应该是没有load colbert_linear参数 https://github.com/NLPJCL/RAG-Retrieval/blob/master/rag_retrieval/train/colbert/model.py#L184。sentence_transformers.CrossEncoder 不能直接加载吗
