### ISSUE TITLE
embedding \rerank微调时，在训练过程中，如何在测试集上eval呢

### ISSUE THREAD

**Issue by HuXiLiFeng** [NLPJCL/RAG-Retrieval#26]
如题，validation_dataloader如何传入呢

**Comment by NLPJCL** [comment]
抱歉，回复的有点晚。
这里已rerank为例子，embedding同理。

1.首先需要仿照train_dataloader,新增加一个validation_dataloader.数据组织格式和train dataset一样。
https://github.com/NLPJCL/RAG-Retrieval/blob/b72716355d7f4a5420920535958740203aa50883/rag_retrieval/train/reranker/train_reranker.py#L115C1-L116C1
2.然后传递进入Trainer，即可。
https://github.com/NLPJCL/RAG-Retrieval/blob/b72716355d7f4a5420920535958740203aa50883/rag_retrieval/train/reranker/train_reranker.py#L148

3.然后每个batch结束后会评测下验证集的loss。

整体trainer比较简单，如果有一些定制化的需求，也可以自行更改。比如多个batch，eval loss没变化就停止等等需求。

**Comment by HuXiLiFeng** [comment]
嗯，已经加好了

**Comment by HuXiLiFeng** [comment]
还可以加每隔一定step在验证集上评估一次，而不是一个epoch完了才评估。有时候在一个epoch内会出现指标最好的点，然后开始下降

**Comment by NLPJCL** [comment]
是的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月4日(周四) 下午3:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [NLPJCL/RAG-Retrieval] embedding \rerank微调时，在训练过程中，如何在测试集上eval呢 (Issue #26)




 
还可以加每隔一定step在验证集上评估一次，而不是一个epoch完了才评估。有时候在一个epoch内会出现指标最好的点，然后开始下降
