### ISSUE TITLE
多GPU怎么改造代码

### ISSUE THREAD

**Issue by shilei4260** [NLPJCL/RAG-Retrieval#3]

**Comment by NLPJCL** [comment]
accelerate支持fsdp,deepspeed等多gpu，目前代码默认多多卡是fsdp。
我简单介绍下目前的代码如何支持多卡：
对于train_embedding.sh
CUDA_VISIBLE_DEVICES="0"改为你想要设置的多卡。
其次，修改https://github.com/NLPJCL/RAG-Retrieval/blob/master/config/default_fsdp.yaml的
num_processes: 1 设置为你想要跑的卡的数量。

**Comment by shilei4260** [comment]
好的
