### ISSUE TITLE
请问之后会支持阿里开源的gte的embedding和rerank模型吗

### ISSUE THREAD

**Issue by LIUKAI0815** [NLPJCL/RAG-Retrieval#31]

**Comment by NLPJCL** [comment]
我大致看了下，感觉可以直接用我们的代码微调，您可以试试，遇到问题在issues说一声就行。

**Comment by NLPJCL** [comment]
https://github.com/NLPJCL/RAG-Retrieval/blob/9d8e00319346a83d6c86f9ff416455822b76270b/rag_retrieval/train/reranker/model.py#L85C1-L86C1

在这里增加trust_remote_code=True。

**Comment by LIUKAI0815** [comment]
感谢，我试一下
