### ISSUE TITLE
为什么向量模型微调后效果更差了

### ISSUE THREAD

**Issue by huangt1** [NLPJCL/RAG-Retrieval#32]
bge和m3e向量模型均使用一万五千条数据微调，loss下降且数据挺好，但是统计发现检出率下降了，这是怎么回事？有什么注意事项吗？
![bge](https://github.com/user-attachments/assets/7516c513-c1a4-4e9d-8a0a-ee229c5667a5)
![m3e](https://github.com/user-attachments/assets/b1e82853-7f94-4704-88dd-cf77959cde9d)

**Comment by NLPJCL** [comment]
通常可能是训练数据和测试数据分布不一致了。
因为不了解具体的场景和数据构造方式，所以没有什么好的建议。

**Comment by huangt1** [comment]
都是针对QA问答检索的场景，正例数据由大模型生成（基于给定问题的回答），负例数据是从检出数据里面选出的不符合答案的数据。如果说是数据分布不一致，那么想问一下负例数据有没有更好的创建方式？随机取样是可能会取到正例数据的，还有其他优化方法吗？

**Comment by NLPJCL** [comment]
负例数据是从检出数据里面选出的不符合答案的数据。
-》》》》
这个是基于向量的难负例挖掘(向量检索出top200，从比如top30-top200里面随机选择一些不属于正例嘛)嘛？

**Comment by NLPJCL** [comment]
> 都是针对QA问答检索的场景，正例数据由大模型生成（基于给定问题的回答），负例数据是从检出数据里面选出的不符合答案的数据。如果说是数据分布不一致，那么想问一下负例数据有没有更好的创建方式？随机取样是可能会取到正例数据的，还有其他优化方法吗？
-》》》》》》》》》》》》》》》
听起来生成的query-answer对应该没什么问题，其实可以做个实验，只用q-a对，然后采用batch 内随机负例，来看下效果。排除下是否是挖掘的负例存在问题。

**Comment by huangt1** [comment]
> 负例数据是从检出数据里面选出的不符合答案的数据。 -》》》》 这个是基于向量的难负例挖掘(向量检索出top200，从比如top30-top200里面随机选择一些不属于正例嘛)嘛？

是的，是从top300-500中挖掘的难负例
