### ISSUE TITLE
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

### ISSUE THREAD

**Issue by ChrisXULC** [NLPJCL/RAG-Retrieval#40]
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
![image](https://github.com/user-attachments/assets/92653b3c-5d56-4da4-9631-9e46ef213f1c)
![image](https://github.com/user-attachments/assets/b792ea5e-be55-43aa-9725-349ffc0c0ed3)

![image](https://github.com/user-attachments/assets/da24c184-ba45-498e-b60b-5d3eaba6a037)
![image](https://github.com/user-attachments/assets/811d1598-4d0e-49e4-87a6-680445538c81)
BTW, how to infer the BGE m3 model with mrl_dims?

**Comment by ChrisXULC** [comment]
![image](https://github.com/user-attachments/assets/9975dc06-7709-4c35-9f58-64e19041c540)
 it worked when I commented this line..

**Comment by NLPJCL** [comment]
For  BGE m3 model with mrl_dims，you can directly use SentenceTransformer infer.

Can you provide the version of your accelerate package?

**Comment by ChrisXULC** [comment]
> For BGE m3 model with mrl_dims，you can directly use SentenceTransformer infer.
> 
> Can you provide the version of your accelerate package?

accelerate            1.0.1
![image](https://github.com/user-attachments/assets/c2307e0b-433f-4e15-b797-63dcb8cdb95b)
is it correct if i want to reduce the dimension to 256?

**Comment by NLPJCL** [comment]
1.OK, this bug is caused by the update of accelerate version(in accelerate  0.34.0 it will disappear ), but it does not affect the model saving because each epoch is saved.
I will find a way to fix it later.

2.is it correct if i want to reduce the dimension to 256?-》〉》〉
it is correct.

3.Thank you for the 500th star:)
