### ISSUE TITLE
微调reranker，可以只放正样本吗？

### ISSUE THREAD

**Issue by lxlx2084** [NLPJCL/RAG-Retrieval#43]
1、
![Snipaste_2024-11-13_21-23-41](https://github.com/user-attachments/assets/50276145-027f-49ee-9521-df7e1e7e1809)
reranker文档里提到的这个neg是难负例吗？还是我自己随机选择几条无关的负例？可不可以只放pos正样本？

2、
我记得embedding里会有batch_size内的随机采样，reranker里有这个机制吗？（如果有的话，那么我只放正样本，也会采样到随机无关负例了，我就不用自己选了）

**Comment by lxlx2084** [comment]
![Snipaste_2024-11-14_22-53-03](https://github.com/user-attachments/assets/21c0b4bb-3fe4-4c26-87c5-875238f0187c)
还有这个超参数怎么理解？

**Comment by NLPJCL** [comment]
> 1、 ![Snipaste_2024-11-13_21-23-41](https://private-user-images.githubusercontent.com/152599454/385775727-50276145-027f-49ee-9521-df7e1e7e1809.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3MjY2MzQsIm5iZiI6MTczMTcyNjMzNCwicGF0aCI6Ii8xNTI1OTk0NTQvMzg1Nzc1NzI3LTUwMjc2MTQ1LTAyN2YtNDllZS05NTIxLWRmN2UxZTdlMTgwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQwMzA1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNWVmMTFlMzM2NGIzOWU2ZTg2ZDMwOTc4ZjU2ZmM2YTcyZmQ4NTI3NzY1OGZlYTk0NDQyZGM5YTljMjQ1ZmRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1FOMi7YTLxKKt6N_2HD6jpJ6mQSSZXzmHmBEfAbd4-M) reranker文档里提到的这个neg是难负例吗？还是我自己随机选择几条无关的负例？可不可以只放pos正样本？
> 
reranker任务一般需要比较难的负例。

> 2、 我记得embedding里会有batch_size内的随机采样，reranker里有这个机制吗？（如果有的话，那么我只放正样本，也会采样到随机无关负例了，我就不用自己选了）
reranker没有，因为对于排序任务来说，随机负例作用不大。
