### ISSUE TITLE
#23、#24里的采样逻辑，有点疑问

### ISSUE THREAD

**Issue by lxlx2084** [NLPJCL/RAG-Retrieval#44]
![Snipaste_2024-11-13_22-30-11](https://github.com/user-attachments/assets/c9e7c867-e9f4-4acc-b554-b4d81be82299)
![Snipaste_2024-11-13_22-30-58](https://github.com/user-attachments/assets/2ed11321-d820-4780-9e42-2a14fed21f76)

这里提到了负例的采样方法，好像有点矛盾，到底是采样batch内其他query的正例还是负例，做为当前query的随机负例？

**Comment by NLPJCL** [comment]
对于只有正例：
1.batch内随机负例是其他query的正样本。
对于有正例也有负例：
1.batch内随机负例是其他query的所有负样本。
