### ISSUE TITLE
微调完的reranker模型，是这样加载吗？

### ISSUE THREAD

**Issue by lxlx2084** [NLPJCL/RAG-Retrieval#45]
![Snipaste_2024-11-14_01-23-54](https://github.com/user-attachments/assets/c8a40ad0-a753-49d3-8558-870e3162b7fc)
![Snipaste_2024-11-14_01-26-31](https://github.com/user-attachments/assets/6db6d1af-4b11-43c7-905d-7172f3bd313b)
1、我把ckpt_path替换成了checkpoint_3，其他不变，然后就可以使用微调后的权重进行compute_score了吗？

2、紧跟上一条，我采用ckpt3去预测，效果和没微调过完全一样。而且微调时一开始的损失也很小（0.07左右），是否说明reranker在预训练时就已经能很好区分这些样本了，得找难负例才能提高？（我的数据是 1个query + 3个pos + 3个无关的样本当做neg，并非难负例）

3、我微调了几次，一开始损失都是0.077，有时能收敛到0.002，但有时损失反而变大，是什么原因呢？

**Comment by NLPJCL** [comment]
1.是的。
2.是的，一般微调reranker模型需要难负例。
3.数据是否一样？
