### ISSUE TITLE
微调相关

### ISSUE THREAD

**Issue by tinaYA524** [NLPJCL/RAG-Retrieval#47]
请问作者大大，基于项目中提供的t2rank_100.jsonl数据，进行BGE模型微调，epoch设置为多少能够复现您的实验结果（提升0.66个点），其他参数是否需要修改？还是默认参数即可？

**Comment by tinaYA524** [comment]
大致看了您提供的数据，包含的内容十分繁杂，是否有更加合规、官方的数据以供微调？

**Comment by tinaYA524** [comment]
不需要特定领域，我想做一个简单的对比实验

**Comment by NLPJCL** [comment]
> 大致看了您提供的数据，包含的内容十分繁杂，是否有更加合规、官方的数据以供微调？

这个是看的example数据吗？还是看的bge的数据？

**Comment by NLPJCL** [comment]
https://huggingface.co/datasets/Shitao/bge-reranker-data
我用的是这个的t2-ranker数据，你可以参考。

**Comment by tinaYA524** [comment]
> > 大致看了您提供的数据，包含的内容十分繁杂，是否有更加合规、官方的数据以供微调？
> 
> 这个是看的example数据吗？还是看的bge的数据？

是的，您项目中的 example_data/t2rank_100.jsonl 数据



> https://huggingface.co/datasets/Shitao/bge-reranker-data 我用的是这个的t2-ranker数据，你可以参考。

好的，我下载下来看一下，万分感谢

**Comment by NLPJCL** [comment]
example 数据只是为了大家跑通代码使用的，只有 100 条。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月21日(周四) 中午12:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [NLPJCL/RAG-Retrieval] 微调相关 (Issue #47)




   
大致看了您提供的数据，包含的内容十分繁杂，是否有更加合规、官方的数据以供微调？
  
这个是看的example数据吗？还是看的bge的数据？
  
是的，您项目中的 example_data/t2rank_100.jsonl 数据
  
https://huggingface.co/datasets/Shitao/bge-reranker-data 我用的是这个的t2-ranker数据，你可以参考。
  
好的，我下载下来看一下，万分感谢
