### ISSUE TITLE
nohup: failed to run command 'accelerate': No such file or directory

### ISSUE THREAD

**Issue by tinaYA524** [NLPJCL/RAG-Retrieval#48]
在A100上进行微调，log报错内容如标题。求作者大大帮助（accelerate我确认安装了 ）

**Comment by NLPJCL** [comment]
这个确实没有见过，可以确认下bash的格式是否正确？

**Comment by tinaYA524** [comment]
> 这个确实没有见过，可以确认下bash的格式是否正确？

我就是按照readme里的步骤做的，
`bash train_embedding.sh
`
还是反复报这个错，我检查了我的环境，版本都是符合要求的，这是为什么呢，烦请解决
