### ISSUE TITLE
A possible bug in llm_rankers.py

### ISSUE THREAD

**Issue by Ziyang1060** [NLPJCL/RAG-Retrieval#52]
There might be a bug in the  llm_rankers.py
https://github.com/NLPJCL/RAG-Retrieval/blob/a60906d1ee6f3ec7242a516b9989e36a793873ab/rag_retrieval/infer/reranker_models/llm_rankers.py#L265

Some tokenizers of LLM models(e.g, Qwen/Qwen2.5-7B-Instruct) might not have bos_token_id (i.e. None).
It will cause a exception: ValueError: type of None unknown: <class 'NoneType'>. Should be one of a python, numpy, pytorch or tensorflow object.

<img width="1070" alt="image" src="https://github.com/user-attachments/assets/2925f293-d3ed-47dc-8e8e-371c3341c9fc">

**Comment by NLPJCL** [comment]
Thanks, For rag-retrieval, it is indeed only applicable to the series reranker model of bge(bge-reranker-v2-gemma,bge-reranker-v2-minicpm-layerwise), but not to the untrained llm model, such as qwen2.5.

**Comment by NLPJCL** [comment]
The readme has been modified. 
https://github.com/NLPJCL/RAG-Retrieval/commit/d941c8758dacf91460b16475ee1ebd86491cb577
