### ISSUE TITLE
关于垂直领域微调Embedding模型数据集的组成？

### ISSUE THREAD

**Issue by PineREN** [NLPJCL/RAG-Retrieval#56]
您好，我想微调训练一个相关文章标题检索的特征提取Embedding模型，需要多少万条数据？是否需要加入通用数据？数据组成比例是怎么样的？感谢！（微信群聊截图过期了）

**Comment by NLPJCL** [comment]
您好，
1.感觉如果微调的话，感觉就k级别或者w级别以下就可以。
2.我觉得如果是只应用于相关文章标题检索。那么不需要加入通用数据。因为现在的embedding模型，已经在通用数据上训练过了。
3.可以加我微信，我拉下。
