### ISSUE TITLE
使用mrl训练的时候报错

### ISSUE THREAD

**Issue by wongbokhe1** [NLPJCL/RAG-Retrieval#58]
CUDA_VISIBLE_DEVICES="1,2,3"   nohup  accelerate launch --config_file ./config/default_fsdp.yaml train_embedding.py  \
--model_name_or_path "/root/autodl-tmp/bxhuang/model_folder/bge-small-zh-v1.5" \
--dataset "/root/autodl-tmp/bxhuang/data_processing/shuiwuju_241202_153w.json" \
--output_dir "./output/ft-bge-small-153w-mrl" \
--batch_size 128 \
--lr 1e-5 \
--epochs 1 \
--use_mrl \
--mrl_dims "128, 256, 512, 768, 1024, 1280, 1536, 1792" \
--save_on_epoch_end 1 \
--gradient_accumulation_steps 4  \
--warmup_proportion 0.1 \
--neg_nums 1 \
--temperature 0.02 \
--query_max_len 128 \
--passage_max_len 128 \
 >./logs/ft-bge-small-153w.log &

[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/autodl-tmp/bxhuang/finetune-bge-small/train_embedding.py", line 188, in <module>
[rank0]:     main()
[rank0]:   File "/root/autodl-tmp/bxhuang/finetune-bge-small/train_embedding.py", line 176, in main
[rank0]:     trainer.train()
[rank0]:   File "/root/autodl-tmp/bxhuang/finetune-bge-small/trainer.py", line 89, in train
[rank0]:     self.save_checkpoint(current_epoch, self.current_step)
[rank0]:   File "/root/autodl-tmp/bxhuang/finetune-bge-small/trainer.py", line 132, in save_checkpoint
[rank0]:     unwrapped_model.save_pretrained(save_dir)
[rank0]:   File "/root/autodl-tmp/bxhuang/finetune-bge-small/model.py", line 249, in save_pretrained
[rank0]:     self.model.save(save_dir, safe_serialization)
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 1139, in save
[rank0]:     module.save(model_path, safe_serialization=safe_serialization)
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/sentence_transformers/models/Dense.py", line 72, in save
[rank0]:     save_safetensors_model(self, os.path.join(output_path, "model.safetensors"))
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/safetensors/torch.py", line 155, in save_model
[rank0]:     to_removes = _remove_duplicate_names(state_dict)
[rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/safetensors/torch.py", line 102, in _remove_duplicate_names
[rank0]:     raise RuntimeError(
[rank0]: RuntimeError: Error while trying to find names to remove to save state dict, but found no suitable name to keep for saving amongst: {'linear.weight'}. None is covering the entire storage.Refusing to save/load the model since you could be storing much more memory than needed. Please refer to https://huggingface.co/docs/safetensors/torch_shared_tensors for more information. Or open an issue.

**Comment by NLPJCL** [comment]
请问是什么时候git clone的代码？
重新git pull更新下代码试试呢？

**Comment by NLPJCL** [comment]
发下保存模型后的：modules.json内容

**Comment by wongbokhe1** [comment]
[
  {
    "idx": 0,
    "name": "0",
    "path": "",
    "type": "sentence_transformers.models.Transformer"
  },
  {
    "idx": 1,
    "name": "1",
    "path": "1_Pooling",
    "type": "sentence_transformers.models.Pooling"
  },
  {
    "idx": 2,
    "name": "2",
    "path": "2_Dense",
    "type": "sentence_transformers.models.Dense"
  }
]

**Comment by NLPJCL** [comment]
no problem



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月16日(周一) 下午4:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [NLPJCL/RAG-Retrieval] 使用mrl训练的时候报错 (Issue #58)




 
[
 {
 "idx": 0,
 "name": "0",
 "path": "",
 "type": "sentence_transformers.models.Transformer"
 },
 {
 "idx": 1,
 "name": "1",
 "path": "1_Pooling",
 "type": "sentence_transformers.models.Pooling"
 },
 {
 "idx": 2,
 "name": "2",
 "path": "2_Dense",
 "type": "sentence_transformers.models.Dense"
 }
 ]

**Comment by wongbokhe1** [comment]
> no problem
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年12月16日(周一) 下午4:28 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [NLPJCL/RAG-Retrieval] 使用mrl训练的时候报错 (Issue #58) [ { "idx": 0, "name": "0", "path": "", "type": "sentence_transformers.models.Transformer" }, { "idx": 1, "name": "1", "path": "1_Pooling", "type": "sentence_transformers.models.Pooling" }, { "idx": 2, "name": "2", "path": "2_Dense", "type": "sentence_transformers.models.Dense" } ] — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

Thanks!
