### ISSUE TITLE
怎么更直观的查看模型效果

### ISSUE THREAD

**Issue by breath1124** [NLPJCL/RAG-Retrieval#6]
在embedding给出的加载模型进行预测示例中，把input编码后打印出张量，我该如何判断我的模型效果
    embedding = Embedding.from_pretrained(
        ckpt_path,
    )
    embedding.to(cuda_device)
    input_lst = ['我喜欢中国','我爱爬泰山']
    embedding = embedding.encode(input_lst,device=cuda_device)
    print(embedding.tolist())

**Comment by NLPJCL** [comment]
您好，可以计算下两个向量的余弦相似度，代表两个文本的相似程度。
