### ISSUE TITLE
Stella Training

### ISSUE THREAD

**Issue by naston** [NLPJCL/RAG-Retrieval#61]
I know that the plan is to release a technical report around this work so some of these questions may be answered in that paper (and I am curious what the general timeline for that paper is). Based on the embedding training code in this repository it seems like the set of fine-tuning data being used is responsible for many of the performance gains compared to mGTE, is this your interpretation as well and will this dataset or the dataset details be released?

**Comment by NLPJCL** [comment]
The Stella model mainly relies on distillation, and its training code has not yet been integrated into rag-retrieval. The report will be released in January 2025.
