### ISSUE TITLE
训练时报错

### ISSUE THREAD

**Issue by chris111110** [NLPJCL/RAG-Retrieval#63]
当我pull最新的代码，用bge m3或者gte ft时，报错如下：
RuntimeError: Error while trying to find names to remove to save state dict, but found no suitable name to keep for saving amongst: {'linear.weight'}. None is covering the entire storage.Refusing to save/load the model since you could be storing much more memory than needed. Please refer to https://huggingface.co/docs/safetensors/torch_shared_tensors for more information. Or open an issue.

**Comment by NLPJCL** [comment]
方便发下具体的报错位置以及运行脚本，帮助我们排查下问题吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月24日(周二) 上午10:11
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [NLPJCL/RAG-Retrieval] 训练时报错 (Issue #63)




 
当我pull最新的代码，用bge m3或者gte ft时，报错如下：
 RuntimeError: Error while trying to find names to remove to save state dict, but found no suitable name to keep for saving amongst: {'linear.weight'}. None is covering the entire storage.Refusing to save/load the model since you could be storing much more memory than needed. Please refer to https://huggingface.co/docs/safetensors/torch_shared_tensors for more information. Or open an issue.

**Comment by chris111110** [comment]
CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7"  accelerate launch --config_file deepspeed_zero1.yaml train_embedding.py  \
--model_name_or_path "/BAAI/bge-m3" \
--dataset "finetune_data.jsonl" \
--output_dir "./output/" \
--batch_size 8 \
--lr 2e-5 \
--epochs 2 \
--use_mrl \
--mrl_dims "128, 384, 512, 768, 1024, 1280, 1536, 1792" \
--save_on_epoch_end 1 \
--gradient_accumulation_steps 32  \
--warmup_proportion 0.1 \
--neg_nums 16 \
--temperature 0.02 \
--query_max_len 128 \
--passage_max_len 256


Traceback (most recent call last):
  File "train/embedding/train_embedding.py", line 186, in <module>
    main()
  File "train/embedding/train_embedding.py", line 174, in main
    trainer.train()
  File "train/embedding/trainer.py", line 107, in train
    unwrapped_model.save_pretrained(save_dir, safe_serialization=True)
  File "/train/embedding/model.py", line 249, in save_pretrained
    self.model.save(save_dir, safe_serialization=safe_serialization)
  File "/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 1165, in save
    module.save(model_path, safe_serialization=safe_serialization)
  File "/lib/python3.10/site-packages/sentence_transformers/models/Dense.py", line 72, in save
    save_safetensors_model(self, os.path.join(output_path, "model.safetensors"))
  File "lib/python3.10/site-packages/safetensors/torch.py", line 155, in save_model
    to_removes = _remove_duplicate_names(state_dict)
  File "lib/python3.10/site-packages/safetensors/torch.py", line 102, in _remove_duplicate_names
    raise RuntimeError(
RuntimeError: Error while trying to find names to remove to save state dict, but found no suitable name to keep for saving amongst: {'linear.weight'}. None is covering the entire storage.Refusing to save/load the model since you could be storing much more memory than needed. Please refer to https://huggingface.co/docs/safetensors/torch_shared_tensors for more information. Or open an issue.

**Comment by NLPJCL** [comment]
这个错误是保存safe_serialization=True导致的，之前也遇到过，应该和一些依赖的版本有关系。（accelerate,transformer）
彻底的解决方法是更新下依赖到最新版本。

比较trick的解决办法是：将下面两个地方保存模型的safe_serialization=True，修改False

https://github.com/NLPJCL/RAG-Retrieval/blob/55b87fb4d19c6fd385a2db162a76970cb74409ee/rag_retrieval/train/embedding/train_embedding.py#L181

https://github.com/NLPJCL/RAG-Retrieval/blob/55b87fb4d19c6fd385a2db162a76970cb74409ee/rag_retrieval/train/embedding/trainer.py#L107C1-L108C1

**Comment by NLPJCL** [comment]
transformers              4.46.1  
实测保存没有这个问题。

**Comment by NLPJCL** [comment]
已经修改默认safe_serialization=False，来适配版本问题。
