### ISSUE TITLE
Code that responsible for concatenating teacher model outputs.

### ISSUE THREAD

**Issue by sigridjineth** [NLPJCL/RAG-Retrieval#66]
Hello, as stated in the pre-published paper, I have noted that outputs from two teacher models are concatenated after inference. As the repository is deemed to be the implementation of the paper, I expect that the logic remains incumbent upon publicising it. However, it seems that there are no relevant codes.

That's I am asking. Thanks for your effort.

**Comment by NLPJCL** [comment]
We will release the training code for Jasper and Stella in the next few days. Thank you.
