### ISSUE TITLE
Hugging face issue显示merged，是否可以删除这两行代码

### ISSUE THREAD

**Issue by zhaoyib** [NLPJCL/RAG-Retrieval#7]
在学习您的Embedding model 的代码的时候，在`save_pretrained`这个函数中，我看到您注释写了有一个hugging face导致的bug，当我去进一步查看那个关于hugging face的issue的时候，发现这个bug好像已经被解决了，[issue链接](https://github.com/UKPLab/sentence-transformers/issues/2533)。我对hugging face保存相关的接口并不熟悉，想请教一下是否可以删除下面这两行代码？
```
merge_command = f"rm  {save_dir}/model.safetensors"
subprocess.run(merge_command, shell=True)
```
期待您的回复。

**Comment by NLPJCL** [comment]
您好，我当时测试虽然issue提到的bug虽然merge了，但是pip上的包还没有更新，所以保留了这两行。
不知道现在是否可以，您可以试试，设置self.model.save(save_dir,safe_serialization=False),然后删除后面贴出的代码，看下是否正常。如果正常的话，欢迎提交pr来更新下～

  #for solve a bug,https://github.com/huggingface/transformers/issues/27293.
  #later upgrade sentence_transformers  will be solve https://github.com/UKPLab/sentence-transformers/issues/2533
  merge_command = f"rm  {save_dir}/model.safetensors"
  subprocess.run(merge_command, shell=True)

  model_state_dict=_trans_state_dict(self.model._modules['0'].state_dict())
  new_model_state_dict={}
  for key,value, in model_state_dict.items():
      new_model_state_dict[key.replace('auto_model.','')]=model_state_dict[key]

**Comment by NLPJCL** [comment]
更新sentence-transformers到最新版本2.7.0后，可以保存了。
目前RAG-Retrieval代码已更新，删除了上述比较trick的解决办法。

**Comment by newsbreakDuadua9** [comment]
This bug still exists, please add it back
when your finetune the model meta-llama/Llama-3.2-3B-Instruct
shared weights are removed again!
